# Work machine profile. Symlink $PROFILE to this file.

$repos = "D:\repos"
$configs = "$repos\misc\configs"

$env:path += ";" + "$repos\pocs\techops-shared\team\charlieb\common"

. "$configs\powershell\common.ps1"

# >>> intelligent-terminal shell-integration >>>
# Auto-generated by Intelligent Terminal. Do not edit between markers.
# Documents is resolved at runtime so this survives OneDrive Known
# Folder Move and is a silent no-op on machines without IT installed.
$__it_si = Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'PowerShell\shell-integration_v6.ps1'
if (Test-Path -LiteralPath $__it_si) { . $__it_si }
Remove-Variable __it_si -ErrorAction SilentlyContinue
# <<< intelligent-terminal shell-integration <<<
