# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.1
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: bat
      settings:
        id: sharkdp.bat
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: neovim
      settings:
        id: Neovim.Neovim
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: eza
      settings:
        id: eza-community.eza
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: fd
      settings:
        id: sharkdp.fd
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ffmpeg
      settings:
        id: Gyan.FFmpeg
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: lazygit
      settings:
        id: JesseDuffield.lazygit
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ohmyposh
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ripgrep
      settings:
        id: BurntSushi.ripgrep.GNU
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: wiztree
      settings:
        id: AntibodySoftware.WizTree
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: notepad++
      settings:
        id: Notepad++.Notepad++
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: neofetch
      settings:
        id: nepnep.neofetch-win
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: windows-terminal
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vlc
      settings:
        id: VideoLAN.VLC
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: git
      settings:
        id: Git.Git
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: obs
      settings:
        id: OBSProject.OBSStudio
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: everything
      settings:
        id: voidtools.Everything
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: slack
      settings:
        id: SlackTechnologies.Slack
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: hwinfo
      settings:
        id: REALiX.HWiNFO
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powertoys
      settings:
        id: Microsoft.PowerToys
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powershell7
      settings:
        id: Microsoft.PowerShell
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: dotnet-sdk-8
      settings:
        id: Microsoft.DotNet.SDK.8
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: llvm
      settings:
        id: LLVM.LLVM
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: cmake
      settings:
        id: Kitware.CMake
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: unzip
      settings:
        id: GnuWin32.UnZip
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nvm
      settings:
        id: CoreyButler.NVMforWindows
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: deno
      settings:
        id: DenoLand.Deno
        source: winget
        allowPrerelease: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: rdcman
      settings:
        id: Microsoft.SysInternals.RDCMan
        source: winget
        allowPrerelease: true
